# Generated by Django 2.0.2 on 2018-03-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='flag',
            new_name='ress',
        ),
    ]
