# Generated by Django 2.0.2 on 2018-03-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20180306_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='ress',
            new_name='flag',
        ),
    ]
