# Generated by Django 2.0.2 on 2018-03-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20180309_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
