# Generated by Django 2.0.2 on 2018-03-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
