# Generated by Django 2.0.2 on 2018-03-12 05:29

from django.db import migrations
from django.db import models
from django.contrib.auth.models import User
from datetime import time
from new.models import  Post


def Add_Post(apps, schema_editor):
    Person = apps.get_model('new', 'Post')
    user_obj = User.objects.get(username='admin')
    Post( privacy = 'public',
          post ="first post from manual data migration",
          user =user_obj,
        ).save()












class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_connect_date'),
    ]

    operations = [

        migrations.RunPython(Add_Post),


    ]



