# Generated by Django 2.0.2 on 2018-03-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_auto_20180312_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='msg',
            field=models.TextField(default='', max_length=20),
        ),
    ]
